source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'BufferKitDemo' do
  # UI Layout
  pod 'SteviaLayout'
  # Colors and themes
  pod 'ChameleonFramework/Swift'
  # Font and icons
  pod 'FontAwesome.swift'
  # JSON <-> Object mapper
  pod 'ObjectMapper', '~> 1.1'
  # Network abstraction layer over Alamofire
  pod 'Moya', '~> 6.2'
  # Progress HUD
  pod 'JGProgressHUD'
  # Empty data set
  pod 'DZNEmptyDataSet'
end

target 'BufferKitDemoTests' do
  pod 'ObjectMapper', '~> 1.1'
  pod 'Moya', '~> 6.2'
end
