source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'BufferKitDemo' do
  pod 'ObjectMapper', '~> 1.1'
  pod 'Moya', '~> 6.2'
  pod 'OAuthSwift', '~> 0.5.0'
end

target 'BufferKitDemoTests' do
  pod 'ObjectMapper', '~> 1.1'
  pod 'Moya', '~> 6.2'
end
